version: "3.7"

services:
   nuxt3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name:  nuxt3
    ports:
      - 3000:3000
    restart: always
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    networks:
      frontend:
        aliases:
          - app

networks:
  frontend:
    name:  nuxt3-network
